- ignore: {name: "Reduce duplication"}
- ignore: {name: "Use infix"}
- ignore: {name: "Use const"}
- ignore: {name: "Parse error"}
# - ignore: {name: "Use camelCase"}
# - ignore: {name: "Use list comprehension", within: [ Console.Pretty.LLVM ] }
# - ignore: {name: "Redundant bracket", within: [ Set.Lazy, Set.Internal, Console.Pretty.LLVM ] }
# - ignore: {name: "Eta reduce", within: [ Set.Lazy, Set.Internal, Automata.Presburger ] }
# - ignore: {name: "Use record patterns", within: [ Set.Lazy, Set.Internal ]  }
# - ignore: {name: "Avoid lambda", within: [ Set.Lazy, Set.Internal ] }
# - ignore: {name: "Use <$>", within: [ Console.Pretty.LLVM ] }
# - ignore: {name: "Use String", within: [ Console.Pretty.LLVM ] }
