- ignore: {name: "Reduce duplication"}
- ignore: {name: "Use infix"}
- ignore: {name: "Use const"}
- ignore: {name: "Parse error"}
- ignore: {name: "Use curry", within: [ Nominal.Category ]}
- ignore: {name: "Use uncurry", within: [ Nominal.Category ]}
